---
- name: Kiểm tra hostname của Linux
  hosts: all
  gather_facts: false

  tasks:
    - name: Lấy hostname của hệ thống
      ansible.builtin.command: hostname
      register: hostname_output

    - name: Hiển thị hostname
      ansible.builtin.debug:
        msg: "Hostname của máy là: {{ hostname_output.stdout }}"
