---
- name: Check uptime of remote server
  hosts: all-linux
  gather_facts: no
  tasks:
    - name: Get Inventory gốc
      set_fact:
        inventory_goc: "{{ group_names | intersect(groups.keys()) | first | default('Unknown') }}"

    - name: Run uptime command
      command: uptime
      register: uptime_result
      ignore_unreachable: yes  # Không dừng khi unreachable

    - name: Display uptime output
      debug:
        msg: "{{ uptime_result.stdout }}"
      when: uptime_result.stdout is defined

    - name: Capture unreachable hosts
      run_once: yes
      set_fact:
        unreachable_hosts: "{{ ansible_play_hosts_all | difference(ansible_play_hosts) }}"

    - name: Send Telegram alert for unreachable hosts
      uri:
        url: "https://api.telegram.org/bot6725419910:AAFPnpMWsIU_kuGFw_RkdjQeyvhzZQ1qxPA/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "-4132281180"
          text: |
            🚨 *CẢNH BÁO LỖI ANSIBLE* 🚨
            ❌ Lỗi trên host: `{{ item }}`
            🏷 Inventory gốc: `{{ hostvars[item].get('inventory_goc', 'Unknown') }}`
            🖥 Hệ điều hành: `{{ 'Windows' if 'win' in hostvars[item].group_names else 'Linux' }}`
          parse_mode: "Markdown"
        headers:
          Content-Type: "application/json"
      loop: "{{ unreachable_hosts }}"
      when: unreachable_hosts | length > 0
