---
- name: Check uptime of remote server
  hosts: all-linux
  gather_facts: no
  tasks:
    - name: Get Inventory gốc
      set_fact:
        inventory_goc: "{{ group_names | intersect(groups.keys()) | first | default('Unknown') }}"

    - name: Run uptime command
      command: uptime
      register: uptime_result
      ignore_errors: yes
      failed_when: uptime_result.rc != 0

    - name: Ghi nhận host unreachable
      set_fact:
        unreachable_hosts: "{{ ansible_play_hosts_all | difference(ansible_play_hosts) }}"
      run_once: yes

    - name: Gửi cảnh báo Telegram khi host bị lỗi
      uri:
        url: "https://api.telegram.org/bot<YOUR_BOT_TOKEN>/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "-4132281180"
          text: |
            🚨 *CẢNH BÁO LỖI ANSIBLE* 🚨
            ❌ Lỗi trên host: `{{ inventory_hostname }}`
            🏷 Inventory gốc: `{{ inventory_goc }}`
            🖥 Hệ điều hành: `{{ 'Windows' if 'win' in group_names else 'Linux' }}`
            📝 Lỗi: `{{ uptime_result.stderr if uptime_result.stderr else 'Unknown error' }}`
          parse_mode: "Markdown"
        headers:
          Content-Type: "application/json"
      when: uptime_result.rc != 0 or uptime_result.failed is defined
      delegate_to: localhost

    - name: Gửi cảnh báo host unreachable
      uri:
        url: "https://api.telegram.org/bot<YOUR_BOT_TOKEN>/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "-4132281180"
          text: |
            🚨 *CẢNH BÁO HOST KHÔNG KẾT NỐI* 🚨
            ❌ Host không kết nối: `{{ item }}`
            🏷 Inventory gốc: `{{ hostvars[item].inventory_goc | default('Unknown') }}`
            🖥 Hệ điều hành: `{{ 'Windows' if 'win' in hostvars[item].group_names else 'Linux' }}`
          parse_mode: "Markdown"
        headers:
          Content-Type: "application/json"
      loop: "{{ unreachable_hosts }}"
      run_once: yes
      delegate_to: localhost
