---
- name: Check uptime of remote server
  hosts: all
  gather_facts: no
  tasks:
    - name: Get Inventory gốc
      set_fact:
        inventory_goc: "{{ group_names | intersect(groups.keys()) | first | default('Unknown') }}"

    - name: Run uptime command
      command: uptime
      register: uptime_result
      ignore_errors: yes

    - name: Ghi nhận host unreachable
      set_fact:
        unreachable_hosts: "{{ ansible_play_hosts_all | difference(ansible_play_hosts) }}"
      run_once: yes

    - name: Gửi cảnh báo Telegram khi host unreachable
      uri:
        url: "https://api.telegram.org/bot<YOUR_BOT_TOKEN>/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "-4132281180"
          text: |
            🚨 *CẢNH BÁO HOST KHÔNG KẾT NỐI* 🚨
            ❌ Host không kết nối: `{{ item }}`
            🏷 Inventory gốc: `{{ hostvars[item].inventory_goc | default('Unknown') }}`
            🖥 Hệ điều hành: `{{ 'Windows' if 'win' in hostvars[item].group_names else 'Linux' }}`
          parse_mode: "Markdown"
        headers:
          Content-Type: "application/json"
      loop: "{{ unreachable_hosts }}"
      run_once: yes
      delegate_to: localhost

    - name: Gửi thông báo Telegram sau khi chạy
      uri:
        url: "https://api.telegram.org/bot<YOUR_BOT_TOKEN>/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "-4132281180"
          text: |
            📝 *KẾT QUẢ CHẠY ANSIBLE* 📝
            🔹 Host: `{{ inventory_hostname }}`
            🏷 Inventory gốc: `{{ inventory_goc }}`
            🖥 Hệ điều hành: `{{ 'Windows' if 'win' in group_names else 'Linux' }}`
            {% if uptime_result.rc is defined and uptime_result.rc == 0 %}
            ✅ *Thành công*: `{{ uptime_result.stdout }}`
            {% else %}
            ❌ *Lỗi*: `{{ uptime_result.stderr if uptime_result.stderr else 'Unknown error' }}`
            {% endif %}
          parse_mode: "Markdown"
        headers:
          Content-Type: "application/json"
      delegate_to: localhost
