---
- name: Check uptime of remote server
  hosts: all-linux
  gather_facts: no
  tasks:
    - name: Get Inventory gốc
      set_fact:
        inventory_goc: "{{ group_names | intersect(groups.keys()) | first | default('Unknown') }}"

    - name: Run uptime command
      command: uptime
      register: uptime_result
      ignore_errors: yes
      failed_when: uptime_result.rc != 0

    - name: Send notification if failure occurs
      uri:
        url: "https://api.telegram.org/bot<YOUR_BOT_TOKEN>/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "-4132281180"
          text: |
            🚨 *CẢNH BÁO LỖI ANSIBLE* 🚨
            ❌ Lỗi trên host: `{{ inventory_hostname }}`
            🏷 Inventory gốc: `{{ inventory_goc }}`
            🖥 Hệ điều hành: `{{ 'Windows' if 'win' in group_names else 'Linux' }}`
            📝 Lỗi: `{{ uptime_result.stderr if uptime_result.stderr else 'Unknown error' }}`
          parse_mode: "Markdown"
        headers:
          Content-Type: "application/json"
      when: uptime_result.rc != 0
      delegate_to: localhost
