- name: Check if IP is in CSF firewall
  hosts: "{{ ip_server }}"
  gather_facts: no
  tasks:
    - name: Run CSF command on remote server
      command: csf -g {{ target_ip }}
      register: csf_output
      changed_when: false

    - name: Display result
      debug:
        msg: "The IP {{ target_ip }} is {{ csf_output.stdout }}."
