- name: Check if IP is in CSF firewall
  hosts: "{{ ip_server }}"
  gather_facts: no
  tasks:
    - name: REMOVE IP command on remote server
      command: csf -g {{ target_ip }}
      register: csf_output
      changed_when: false
