- name: Check system information
  hosts: all
  gather_facts: yes
  tasks:
    - name: Get OS version
      shell: "cat /etc/os-release | grep '^PRETTY_NAME=' | cut -d '=' -f2 | tr -d '\"'"
      register: os_version

    - name: Get hostname
      command: hostname
      register: hostname_output

    - name: Get disk usage
      command: "df -h --output=source,size,used,avail,pcent,target / | tail -1"
      register: disk_usage

    - name: Get memory usage
      shell: "free -m | awk 'NR==2 {print \"Total: \"$2\" MB, Used: \"$3\" MB, Free: \"$4\" MB\"}'"
      register: memory_usage

    - name: Get IP address
      shell: "hostname -I | awk '{print $1}'"
      register: ip_address
      ignore_errors: yes

    - name: Print system information
      debug:
        msg: |
          OS Version: {{ os_version.stdout }}
          Hostname: {{ hostname_output.stdout }}
          Disk Usage: {{ disk_usage.stdout }}
          Memory Usage: {{ memory_usage.stdout }}
          IP Address: {{ ip_address.stdout | default('Not Found') }}
