---
- name: Xác định Inventory gốc
  hosts: all-linux
  set_fact:
    inventory_goc: "{{ group_names | intersect(groups.keys()) | first | default('Unknown') }}"
- name: Check uptime of remote server
  hosts: all-linux
  gather_facts: no
  tasks:
    - name: Run uptime command
      command: uptime
      register: uptime_result

    - name: Display uptime output
      debug:
        msg: "{{ uptime_result.stdout }}"
