---
- name: Check uptime and determine root inventory
  hosts: all-linux
  gather_facts: no

  tasks:
    - name: Xác định inventory gốc chính xác
      set_fact:
        root_inventory: >-
          {{
            groups.keys()
            | difference(['all', 'ungrouped', 'all-linux', 'all-win'])
            | select('in', group_names)
            | list
            | first
            | default('unknown')
          }}

    - name: Lấy uptime trên Linux
      command: uptime
      register: uptime_result
      when: "'Linux' in ansible_os_family"
      ignore_errors: yes

    - name: Hiển thị thông tin
      debug:
        msg: >-
          🖥 Host: {{ inventory_hostname }} ({{ ansible_host }})
          🏷 Inventory gốc: {{ root_inventory }}
          ⏳ Uptime: {{ uptime_result.stdout | default('Không lấy được') }}
