- name: Check Uptime và gửi Telegram
  hosts: all
  gather_facts: no
  tasks:
    - name: Lấy uptime
      command: uptime -p
      register: uptime_result

    - name: Gửi kết quả lên Telegram
      uri:
        url: "https://api.telegram.org/bot<BOT_TOKEN>/sendMessage"
        method: POST
        body:
          chat_id: "-4132281180"
          text: "📢 Máy chủ {{ inventory_hostname }} đã chạy được: {{ uptime_result.stdout }}"
        body_format: json
        headers:
          Content-Type: "application/json"
