---
- name: Xác định Inventory gốc và gửi Telegram
  hosts: all-linux
  gather_facts: no
  tasks:
    - name: Xác định Inventory gốc chính xác
      set_fact:
        inventory_goc: >-
          {{
            groups.keys()
            | difference(['all', 'ungrouped', 'linux', 'win', 'all-linux', 'all-win'])
            | select('search', '.*')
            | select('reject', 'match', '^(win|linux)$')  # Bỏ nhóm con
            | select('selectattr', '1', 'contains', inventory_hostname, groups)
            | map('first')
            | list
            | first
            | default('Unknown')
          }}

    - name: Lấy thông tin uptime
      command: uptime -p
      register: uptime_result
      changed_when: false

    - name: Debug kiểm tra nhóm thực sự
      debug:
        msg: "Host {{ inventory_hostname }} thuộc Inventory gốc: {{ inventory_goc }}, Uptime: {{ uptime_result.stdout }}"

    - name: Gửi thông báo Telegram
      uri:
        url: "https://api.telegram.org/bot<BOT_TOKEN>/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "-4132281180"
          text: |
            🚨 *THÔNG BÁO INVENTORY* 🚨
            🖥 Host: `{{ inventory_hostname }}`
            🏷 Inventory gốc: `{{ inventory_goc }}`
            ⏳ Uptime: `{{ uptime_result.stdout }}`
        headers:
          Content-Type: "application/json"
      when: inventory_goc != "Unknown"
