- name: Xác định Inventory gốc và gửi Telegram
  hosts: all-linux
  gather_facts: no
  tasks:
    - name: Xác định Inventory gốc
      set_fact:
        inventory_goc: "{{ group_names | difference(['all-linux']) | intersect(groups.keys()) | first | default('Unknown') }}"

    - name: Gửi thông báo Telegram
      uri:
        url: "https://api.telegram.org/bot6725419910:AAFPnpMWsIU_kuGFw_RkdjQeyvhzZQ1qxPA/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "-4132281180"
          text: |
            🚨 *THÔNG BÁO INVENTORY* 🚨
            🖥 Host: {{ inventory_hostname }}
            🏷 Inventory gốc: {{ inventory_goc }}
        headers:
          Content-Type: "application/json"
