---
- name: Xác định Inventory gốc chính xác
  hosts: all-linux
  gather_facts: no
  tasks:
    - name: Xác định Inventory gốc
      set_fact:
        inventory_goc: >-
          {{
            groups.keys()
            | difference(["all", "ungrouped", "linux", "win", "all-linux", "all-win"])  # Chỉ lấy inventory gốc
            | select('search', '^.+$')  # Chọn tất cả group hợp lệ
            | select('selectattr', '0', 'in', groups)  # Chỉ lấy group có children
            | select('selectattr', '0', 'in', groups[inventory_hostname] | default([]))  # Kiểm tra host có trong group nào
            | list
            | first
            | default('Unknown')
          }}

    - name: Debug kiểm tra nhóm thực sự
      debug:
        msg: "Host {{ inventory_hostname }} thuộc Inventory gốc: {{ inventory_goc }}"
