---
- name: Check uptime and determine root inventory
  hosts: all
  gather_facts: no  # Không cần facts để tránh lỗi ansible_os_family

  vars:
    telegram_bot_token: "6725419910:AAFPnpMWsIU_kuGFw_RkdjQeyvhzZQ1qxPA"
    telegram_chat_id: "-4132281180"

  tasks:
    - name: Xác định inventory gốc chính xác
      set_fact:
        root_inventory: >-
          {{
            groups.keys()
            | difference(['all', 'ungrouped', 'all-linux', 'all-win'])
            | select('in', group_names)
            | list
            | first
            | default('unknown')
          }}

    - name: Lấy uptime trên Linux
      command: uptime
      register: uptime_result
      ignore_errors: yes  # Tránh lỗi khi không lấy được uptime

    - name: Hiển thị thông tin
      debug:
        msg: >-
          🖥 Host: {{ inventory_hostname }} ({{ ansible_host }})
          🏷 Inventory gốc: {{ root_inventory }}
          ⏳ Uptime: {{ uptime_result.stdout | default('Không lấy được') }}

        - name: Gửi thông báo Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: >-
            🖥 Host: {{ inventory_hostname }} ({{ ansible_host }})
            📂 Inventory gốc: {{ root_inventory }}
            
            ⏳ Uptime:
            {{ uptime_result.stdout | default('Không lấy được') }}
        headers:
          Content-Type: "application/json"
