---
- name: Check uptime and identify root inventory
  hosts: all-linux
  gather_facts: no

  tasks:
    - name: Xác định inventory gốc
      set_fact:
        root_inventory: >-
          {{
            group_names
            | select('search', '^[a-zA-Z0-9]+$')  # Chỉ lấy nhóm không chứa ký tự đặc biệt
            | difference(['all', 'ungrouped'])
            | first | default('unknown')
          }}

    - name: Lấy uptime trên Linux
      command: uptime
      register: uptime_result
      ignore_errors: yes

    - name: Hiển thị thông tin
      debug:
        msg: >-
          🖥 Host: {{ inventory_hostname }} ({{ ansible_host }})
          🏷 Inventory gốc: {{ root_inventory }}
          ⏳ Uptime: {{ uptime_result.stdout | default('Không lấy được') }}
