---
- name: Check uptime and identify root inventory
  hosts: all-linux
  gather_facts: no

  tasks:
    - name: Xác định nhóm inventory gốc
      set_fact:
        root_group: >-
          {{
            group_names
            | map('regex_replace', '(-linux|-win)$', '')  # Loại bỏ hậu tố nhóm con
            | difference(['all', 'ungrouped', 'linux', 'win', 'all-linux', 'all-win'])
            | first | default('unknown')
          }}

    - name: Lấy uptime bằng lệnh đơn giản
      command: uptime
      register: uptime_result
      ignore_errors: yes  # Bỏ qua lỗi nếu không lấy được uptime

    - name: Debug thông tin uptime
      debug:
        msg: >-
          🖥 Host: {{ inventory_hostname }} ({{ ansible_host }})
          🏷 Inventory gốc: {{ root_group }}
          ⏳ Uptime: {{ uptime_result.stdout | default('Không lấy được') }}
