---
- name: Xác định Inventory gốc và kiểm tra uptime
  hosts: all-linux
  gather_facts: no
  tasks:
    - name: Xác định Inventory gốc
      set_fact:
        inventory_goc: "{{ group_names | intersect(groups.keys()) | first | default('Unknown') }}"

    - name: Run uptime command
      command: uptime
      register: uptime_result

    - name: Display uptime output
      debug:
        msg: "{{ uptime_result.stdout }}"
