- name: Check Uptime trên các máy chủ
  hosts: all-linux
  gather_facts: no
  tasks:
    - name: Lấy uptime của máy chủ
      command: uptime
      register: uptime_result

    - name: Hiển thị kết quả uptime
      debug:
        msg: "Uptime của {{ inventory_hostname }}: {{ uptime_result.stdout }}"
