---
- name: Check uptime and group membership with Telegram notification
  hosts: all-linux
  gather_facts: yes
  
  vars:
    telegram_bot_token: "6725419910:AAFPnpMWsIU_kuGFw_RkdjQeyvhzZQ1qxPA"  # Thay bằng token của bạn
    telegram_chat_id: "-4132281180"     # Thay bằng chat ID của bạn

  tasks:
    - name: Get uptime for Windows hosts
      win_command: powershell.exe "Get-Uptime | Format-List"
      register: win_uptime
      when: ansible_os_family == "Windows"

    - name: Get uptime for Linux hosts
      command: uptime
      register: linux_uptime
      when: ansible_os_family == "Linux"

    - name: Determine root group name
      set_fact:
        root_group: "{{ group_names | intersect(['datnguyen']) | first | default('unknown') }}"
      when: group_names is defined

    - name: Store result in variable
      set_fact:
        host_info: "{{ ansible_host }} / {{ root_group }}"

    - name: Display IP and group membership
      debug:
        msg: "{{ host_info }}"

    - name: Send Telegram notification
      delegate_facts: true
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body: 
          chat_id: "{{ telegram_chat_id }}"
          text: "{{ host_info }}\nUptime: {{ linux_uptime.stdout if ansible_os_family == 'Linux' else win_uptime.stdout }}"
        status_code: 200
      register: telegram_result
      failed_when: telegram_result.status != 200
