---
- name: Check uptime and group membership with Telegram notification
  hosts: all-linux
  gather_facts: no  # Không cần gather_facts giúp chạy nhanh hơn

  vars:
    telegram_bot_token: "6725419910:AAFPnpMWsIU_kuGFw_RkdjQeyvhzZQ1qxPA"
    telegram_chat_id: "-4132281180"
    exclude_groups: ['all', 'ungrouped', 'linux', 'win', 'all-linux', 'all-win']

  tasks:
    - name: Debug danh sách group có thể có host này
      debug:
        msg: "{{ item }}"
      loop: "{{ groups.keys() | difference(exclude_groups) }}"
      when: inventory_hostname in groups[item]

    - name: Xác định Inventory gốc chính xác
      set_fact:
        root_inventory: >-
          {{ groups.keys() | difference(exclude_groups)
          | select('match', '^[a-zA-Z0-9_-]+$')
          | select('extract', groups, inventory_hostname in groups[item])
          | list | first | default('unknown') }}

    - name: Debug Inventory gốc
      debug:
        msg: "Inventory gốc: {{ root_inventory }}"

    - name: Lấy uptime trên Linux
      command: uptime
      register: linux_uptime
      ignore_errors: yes

    - name: Gửi thông báo Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            🖥 *Host:* `{{ inventory_hostname }} ({{ ansible_host }})`
            📂 *Inventory gốc:* `{{ root_inventory }}`
            ⏳ *Uptime:* `{{ linux_uptime.stdout | default('Không lấy được') }}`
        headers:
          Content-Type: "application/json"
        status_code: 200
      register: telegram_result
      failed_when: telegram_result.status != 200
      when: telegram_bot_token is defined and telegram_chat_id is defined
