---
- name: Xác định Inventory gốc và gửi Telegram
  hosts: all-linux
  gather_facts: no
  tasks:
    - name: Xác định Inventory gốc chính xác
      set_fact:
        inventory_goc: >-
          {{
            groups.keys()
            | difference(["all", "ungrouped", "linux", "win", "all-linux", "all-win"])
            | select('equalto', inventory_hostname, groups)
            | list
            | first
            | default('Unknown')
          }}

    - name: Debug kiểm tra nhóm thực sự
      debug:
        msg: "Host {{ inventory_hostname }} thuộc Inventory gốc: {{ inventory_goc }}"

    - name: Gửi thông báo Telegram
      uri:
        url: "https://api.telegram.org/bot6725419910:AAFPnpMWsIU_kuGFw_RkdjQeyvhzZQ1qxPA/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "-4132281180"
          text: |
            🚨 *THÔNG BÁO INVENTORY* 🚨
            🖥 Host: `{{ inventory_hostname }}`
            🏷 Inventory gốc: `{{ inventory_goc }}`
        headers:
          Content-Type: "application/json"
