---
- name: Check uptime and identify root inventory
  hosts: host-linux
  gather_facts: yes
  
  tasks:
    - name: Xác định nhóm inventory gốc
      set_fact:
        root_group: "{{ group_names | intersect(['khangbui', 'vanthanh']) | first | default('unknown') }}"
      when: group_names is defined

    - name: Lấy uptime trên Linux
      command: uptime -p
      register: linux_uptime
      when: ansible_os_family == "Linux"

    - name: Lấy uptime trên Windows
      win_shell: "(get-date) - (gcim Win32_OperatingSystem).LastBootUpTime"
      register: win_uptime
      when: ansible_os_family == "Windows"

    - name: Debug thông tin uptime
      debug:
        msg: >-
          🖥 Host: {{ inventory_hostname }} ({{ ansible_host }})
          🏷 Inventory gốc: {{ root_group }}
          ⏳ Uptime: {{
            linux_uptime.stdout if ansible_os_family == "Linux" else
            win_uptime.stdout if ansible_os_family == "Windows" else
            'Không lấy được'
          }}
