---
- name: Check uptime and Inventory gốc, send Telegram notification
  hosts: all-linux
  gather_facts: no
  tasks:

    - name: Kiểm tra kết nối SSH
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        timeout: 5
      delegate_to: localhost
      register: ssh_status
      ignore_errors: yes

    - name: Lấy Uptime trên Linux
      command: uptime
      register: uptime_result
      when: ssh_status is succeeded
      changed_when: false
      ignore_errors: yes

    - name: Debug Uptime Output
      debug:
        msg: "{{ uptime_result.stdout | default('Không lấy được') }}"

    - name: Xác định Inventory gốc
      set_fact:
        root_inventory: >-
          {{ groups.keys() | difference(['all', 'ungrouped', 'linux', 'win', 'all-linux', 'all-win'])
          | select('match', '^[a-zA-Z0-9_-]+$')
          | selectattr(inventory_hostname, 'in', groups)
          | list | first | default('unknown') }}

    - name: Debug Inventory gốc
      debug:
        msg: "Inventory gốc: {{ root_inventory }}"

    - name: Tạo nội dung thông báo Telegram
      set_fact:
        telegram_message: |
          🖥 *Host:* `{{ inventory_hostname }} ({{ ansible_default_ipv4.address | default('N/A') }})`
          📂 *Inventory gốc:* `{{ root_inventory }}`
          ⏳ *Uptime:* `{{ uptime_result.stdout | default('🔴 Không lấy được') }}`

    - name: Gửi thông báo Telegram
      uri:
        url: "https://api.telegram.org/bot{{ TELEGRAM_BOT_TOKEN }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ TELEGRAM_CHAT_ID }}"
          text: "{{ telegram_message }}"
          parse_mode: "Markdown"
      when: uptime_result is defined
