---
- name: Check Disk Usage on Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Get Disk Usage
      win_shell: Get-PSDrive -Name C | Select-Object Used, Free
      register: disk_usage

    - name: Show Disk Usage
      debug:
        msg: "Used: {{ disk_usage.stdout_lines[2] }}, Free: {{ disk_usage.stdout_lines[3] }}"
